name: Lint

on: [push]

jobs:
  tflint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        uses: docker://wata727/tflint

  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: terraform fmt --recursive 

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - name: Validate Code
        run: |
          terraform init
          terraform validate
      - name: Validate Examples
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd $example
            terraform init
            terraform validate
            cd -
          done